---
- name: My Test Application
  hosts: all
  become: true
  tasks:
    - name: Stop the Service
      service:
        name: httpd
        state: stopped

    - name: Delete the Docker app
      yum:
        name: httpd*
        state: removed
...
