---
- name: Installation of docker app
  hosts: all
  become: yes
  tasks:
    - name: Install the Docker Pkg.
      package: 
        name: docker 
        state: present
        update_cache: yes

    - name: start the service
      service:
        name: docker
        state: started 
...


