---
- name: My Test Application
  hosts: all
  become: true
  tasks:
    - name: Install Packages
      yum:
        name: ['git','make','gcc','wget','telnet','tree','which','docker']
        state: installed
...
