---
# tasks file for setup-apache-role
- name: Install httpd package on RedHat Package
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
  notify: Start httpd service

- name: Install apache2 package on Debian Package
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache2 service

- name: Copy index.html file
  copy:
    src: /home/ansadmin/index.html
    dest: /var/www/html
    mode: 0777
